<script>
    /*
    Pending:
    Resolve: then()
    Reject: catch()
    */
   let p1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        console.log('Logic to fetch the Data: Failure');
        reject();
    },5000)
   });

   p1.then((data)=> {
    console.log('Process the received Data: ',data);
   }).catch(()=> {
    console.log('Error occured while fetching the data');
   })
</script>